version: '3'
services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      VERSION: "1.17.1"
      EULA: "TRUE"
      TYPE: "SPIGOT"
      OPS: "Rexter_Kuro"
      PAPER: "TRUE"
      BUILDTools: "TRUE"
    stdin_open: true
    tty: true
    volumes:
      - ./data:/data
      - ./plugins:/plugins
    restart: always
