version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft_server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "SPIGOT"
      VERSION: "1.20.6"
    volumes:
      - "./minecraft_data:/data"
    restart: always
